

#include	"tn_defs.h"

int tempint[] = {
CAT_ROOT_SEQ          ,
CAT_SLEEP_SEQ         ,
CAT_BOMB_SEQ          ,
CAT_WALK_SEQ          ,
CAT_CRACK_SEQ         ,
CAT_SHAKE_SEQ         ,
CAT_RUN_SEQ           ,
CAT_HAIR_SEQ          ,
CAT_BIRDS_SEQ         ,
CAT_FLAIL_SEQ         ,
CAT_UNUSED1_SEQ       ,
CAT_UNUSED2_SEQ       ,
CAT_UNUSED3_SEQ       ,
CAT_UNUSED4_SEQ       ,
CAT_POUNCE_SEQ        ,
CAT_YARN_SEQ          ,
CAT_SHOT_SEQ          ,
CAT_ANGEL_SEQ         ,
CAT_SPIN_SEQ          ,
CAT_SKID_SEQ          ,
CAT_ATE_SEQ           ,
CAT_RUNAW_SEQ         ,
CAT_SPINAW_SEQ        ,
CAT_TAKE_SEQ          ,
CAT_CLIMB_SEQ         ,
CAT_CUT_SEQ           ,
CAT_STOP_SEQ          ,
CAT_HIT_FLOOR_SEQ     ,
CAT_HIT_CEILING_SEQ   ,
CAT_HIT_LEFT_WALL_SEQ ,
CAT_HIT_RIGHT_WALL_SEQ,
CAT_SLIDE1_SEQ        ,
CAT_SLIDE2_SEQ        ,
CAT_SLIDE3_SEQ        ,
CAT_SLIDE4_SEQ        ,
CAT_PIN1_SEQ          ,
CAT_PIN2_SEQ          ,
CAT_PIN3_SEQ          ,
CAT_VAC1_SEQ          ,
CAT_VAC2_SEQ          ,
CAT_VAC3_SEQ          ,
CAT_PIANO_SEQ         ,
CAT_GUM_SEQ           ,
CAT_BUTT_SEQ          ,
CAT_LUNCH_SEQ         ,
CAT_TUNNEL_SEQ        ,
CAT_PENCIL1_SEQ       ,
CAT_PENCIL2_SEQ       ,
CAT_SCRATCH_SEQ       ,
CAT_PENCIL4_SEQ       ,
CAT_FISH_SEQ          ,
CAT_HAIRDRYER_SEQ     ,
CAT_MIRROR1_SEQ       ,
CAT_MIRROR2_SEQ       ,
CAT_PEEL_SEQ          ,
CAT_BANANA_SEQ        ,
CAT_RUG_SEQ           ,
CAT_GUM2_SEQ          ,
CAT_GUM3_SEQ          ,
CAT_EGG_SEQ           ,
CAT_NUM_STATES        };


char *tempname[] = {
"CAT_ROOT_SEQ          ",
"CAT_SLEEP_SEQ         ",
"CAT_BOMB_SEQ          ",
"CAT_WALK_SEQ          ",
"CAT_CRACK_SEQ         ",
"CAT_SHAKE_SEQ         ",
"CAT_RUN_SEQ           ",
"CAT_HAIR_SEQ          ",
"CAT_BIRDS_SEQ         ",
"CAT_FLAIL_SEQ         ",
"CAT_UNUSED1_SEQ       ",
"CAT_UNUSED2_SEQ       ",
"CAT_UNUSED3_SEQ       ",
"CAT_UNUSED4_SEQ       ",
"CAT_POUNCE_SEQ        ",
"CAT_YARN_SEQ          ",
"CAT_SHOT_SEQ          ",
"CAT_ANGEL_SEQ         ",
"CAT_SPIN_SEQ          ",
"CAT_SKID_SEQ          ",
"CAT_ATE_SEQ           ",
"CAT_RUNAW_SEQ         ",
"CAT_SPINAW_SEQ        ",
"CAT_TAKE_SEQ          ",
"CAT_CLIMB_SEQ         ",
"CAT_CUT_SEQ           ",
"CAT_STOP_SEQ          ",
"CAT_HIT_FLOOR_SEQ     ",
"CAT_HIT_CEILING_SEQ   ",
"CAT_HIT_LEFT_WALL_SEQ ",
"CAT_HIT_RIGHT_WALL_SEQ",
"CAT_SLIDE1_SEQ        ",
"CAT_SLIDE2_SEQ        ",
"CAT_SLIDE3_SEQ        ",
"CAT_SLIDE4_SEQ        ",
"CAT_PIN1_SEQ          ",
"CAT_PIN2_SEQ          ",
"CAT_PIN3_SEQ          ",
"CAT_VAC1_SEQ          ",
"CAT_VAC2_SEQ          ",
"CAT_VAC3_SEQ          ",
"CAT_PIANO_SEQ         ",
"CAT_GUM_SEQ           ",
"CAT_BUTT_SEQ          ",
"CAT_LUNCH_SEQ         ",
"CAT_TUNNEL_SEQ        ",
"CAT_PENCIL1_SEQ       ",
"CAT_PENCIL2_SEQ       ",
"CAT_SCRATCH_SEQ       ",
"CAT_PENCIL4_SEQ       ",
"CAT_FISH_SEQ          ",
"CAT_HAIRDRYER_SEQ     ",
"CAT_MIRROR1_SEQ       ",
"CAT_MIRROR2_SEQ       ",
"CAT_PEEL_SEQ          ",
"CAT_BANANA_SEQ        ",
"CAT_RUG_SEQ           ",
"CAT_GUM2_SEQ          ",
"CAT_GUM3_SEQ          ",
"CAT_EGG_SEQ           ",
"CAT_NUM_STATES        " };

int main(void)
{

	int	i;
	int 	j;

	j = sizeof(tempint)/sizeof(int);

	for (i=0;i<j;i++)
		printf("#define\t%s\t%d\n",tempname[i], tempint[i]);

	return(0);
}



