

/* --- Portable types (unlike char, int, short, and long) --- */

typedef unsigned short BOOL;		/* boolean */

typedef signed   char  SBYTE;		/* signed    8-bit number */
typedef unsigned char  UBYTE;		/* unsigned  8-bit number */
typedef signed   int   SWORD;		/* signed   16-bit number */
typedef unsigned int   UWORD;		/* unsigned 16-bit number */
typedef signed   long  SLONG;		/* signed   32-bit number */
typedef unsigned long  ULONG;		/* unsigned 32-bit number */

typedef signed   short FIX16;		/* signed  8.8  fixed point fraction */
typedef signed   long  FIX32;		/* signed 16.16 fixed point fraction */


