	dc.b	13		; number of sequences is 13
	dc.b	'IRSHWASH'	; name of sequence 0
	dc.b	'TMT_POET'	; name of sequence 1
	dc.b	'TOONSTHM'	; name of sequence 2
	dc.b	'BLUDANUB'	; name of sequence 3
	dc.b	'GRNFINAL'	; name of sequence 4
	dc.b	'LVBSYMP5'	; name of sequence 5
	dc.b	'MITYFORT'	; name of sequence 6
	dc.b	'SIERRA'	; name of sequence 7
	dc.b	'FREEJAZZ'	; name of sequence 8
	dc.b	'TMT_ARAB'	; name of sequence 9
	dc.b	'TMT_BRBR'	; name of sequence 10
	dc.b	'TMT_CAN'	; name of sequence 11
	dc.b	'TMT_CLSA'	; name of sequence 12
