



	XREF	SetVDPRegs
	XREF	SetVDPDMA
	XREF	ScanJoy1
	XREF	ScanJoy2
	XREF	ClearKeys
	XREF	WaitFrame
	XREF	WaitFrames
	XREF	SetVRAMWrite
	XREF	SetVRAMRead
	XREF	SetCRAMWrite
	XREF	SetCRAMRead
	XREF	SetVSRAMWrite
	XREF	SetVSRAMRead
	XREF	BlackOut
	XREF	SetPalette
	XREF	FadeIn
	XREF	FadeOut
	XREF	WaitForDMA
	XREF	ClearVRAM
	XREF	ClearVSRAM
	XREF	ClearHSRAM
	XREF	CopyToVRAM
	XREF	CopyToVRAM2
	XREF	VerticalGrid
	XREF	LoadCellMap
	XREF	LoadChars
	XREF	ClearCellMap
	XREF	SetCellBlock
	XREF	LoadZ80	
	XREF	AddDMAQueue

