/* * * * *
*
*  TOONS.H
*
*  This file contains all the includes necessary for the new toons modules.
*
*  By Chris Cole -- (c) 1993 Dynamix Software Development, Inc.
*
*  Modification History:
*  ---------------------
*  03/08/93 ChrisC   File created
*
* * * * */
#ifndef TOONS_H
#define TOONS_H

#include "tn_func.h"
#include "tn_defs.h"
#include "tn_glob.h"
#include "jtp_sx.h"
/* #include "jtp_hds.h"

#include "debug.h" */

#endif
