**************************************************************************
**                              VARIABLES                                *
**************************************************************************

	XREF	FlyBackFlag
	XREF	KeyHit
	XREF	KeyTab1
	XREF	KeyTab2
	XREF	CellMapCols
	XREF	CellMapRows
	XREF	DMATemp
	XREF	PalBuffer
	XREF	_MapABuff
	XREF	_MapBBuff
	XREF	_SYS_FirstChar
	XREF	_SYS_LastChar
	XREF	_SYS_VDPAccess
	XREF	_MapX
	XREF	_MapY
	XREF	_SYS_JoyHit
	XREF	_SYS_JoyTable,_SYS_JoyTable2
	XREF	_SYS_VCount
