rem copy \toons\tom\part18.anm
copy \toons\tom\part26.anm
copy \toons\tom\part27.anm
copy \toons\tom\part28.anm
copy \toons\tom\part29.anm
rem copy \toons\tom\part3.anm
rem copy \toons\tom\part46.anm
copy \toons\tom\part48.anm
copy \toons\tom\part49.anm
copy \toons\tom\part50.anm
copy \toons\tom\part51.anm
copy \toons\tom\part82.anm
copy \toons\tom\part83.anm
copy \toons\tom\part84.anm

rem del part18.fpa
del part26.fpa
del part27.fpa
del part28.fpa
del part29.fpa
rem del part3.fpa
rem del part46.fpa
del part48.fpa
del part49.fpa
del part50.fpa
del part51.fpa
del part82.fpa
del part83.fpa
del part84.fpa
